# services:
#   - type: web
#     name: parse-m
#     runtime: node
#     plan: free
#     buildCommand: pnpm install; pnpm build
#     startCommand: pnpm start
#     autoDeploy: false
#     envVars:
#       - key: PORT
#         value: 10000

services:
  - name: my-next-puppeteer-app
    dockerfilePath: ./Dockerfile
    env:
      NODE_ENV: production
      PORT: 3000
    ports:
      - port: 3000
    healthCheckPath: "/"
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"