services:
  - type: web
    name: parse-m
    runtime: node
    plan: free
    buildCommand: pnpm install; pnpm build
    startCommand: pnpm start
    autoDeploy: false
    envVars:
      - key: PORT
        value: 10000
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
